
litellm_settings:
  drop_params: true
  set_verbose: true
  

model_list:
  - model_name: "[Anthropic] Claude 3 Haiku"
    litellm_params:
      model: anthropic/claude-3-haiku-20240307
      api_key: os.environ/ANTHROPIC_API_KEY
  - model_name: "[Anthropic] Claude 3.5 Sonnet"
    litellm_params:
      model: anthropic/claude-3-5-sonnet-20240620
      api_key: os.environ/ANTHROPIC_API_KEY
  
  - model_name: "[Cohere] Command R"
    litellm_params:
      model: cohere/command-r
      api_key: os.environ/COHERE_API_KEY
  - model_name: "[Cohere] Command R+"
    litellm_params:
      model: cohere/command-r-plus
      api_key: os.environ/COHERE_API_KEY
  - model_name: "[Cohere] Command R (8/24)"
    litellm_params:
      model: cohere/command-r-08-2024
      api_key: os.environ/COHERE_API_KEY
  - model_name: "[Cohere] Command R+ (8/24)"
    litellm_params:
      model: cohere/command-r-plus-08-2024
      api_key: os.environ/COHERE_API_KEY
  
  - model_name: "[Google] Gemini 1.5 Flash"
    litellm_params:
      model: gemini/gemini-1.5-flash
      api_key: os.environ/GOOGLE_API_KEY
  - model_name: "[Google] Gemini 1.5 Pro"
    litellm_params:
      model: gemini/gemini-1.5-pro
      api_key: os.environ/GOOGLE_API_KEY
  - model_name: "[Google] Gemini 1.0 Pro"
    litellm_params:
      model: gemini/gemini-1.0-pro
      api_key: os.environ/GOOGLE_API_KEY
  - model_name: "[Google] Gemma 2 (2B)"
    litellm_params:
      model: gemini/gemma-2-2b-it
      api_key: os.environ/GOOGLE_API_KEY
  - model_name: "[Google] Gemma 2 (9B)"
    litellm_params:
      model: gemini/gemma-2-9b-it
      api_key: os.environ/GOOGLE_API_KEY
  - model_name: "[Google] Gemma 2 (27B)"
    litellm_params:
      model: gemini/gemma-2-27b-it
      api_key: os.environ/GOOGLE_API_KEY
  
  - model_name: "[Groq] Gemma 1 (7B)"
    litellm_params:
      model: groq/gemma-7b-it
      api_key: os.environ/GROQ_API_KEY
  - model_name: "[Groq] Gemma 2 (9B)"
    litellm_params:
      model: groq/gemma2-9b-it
      api_key: os.environ/GROQ_API_KEY
  - model_name: "[Groq] Llama 3.1 (70B)"
    litellm_params:
      model: groq/llama-3.1-70b-versatile
      api_key: os.environ/GROQ_API_KEY
  - model_name: "[Groq] Llama 3.1 (8B)"
    litellm_params:
      model: groq/llama-3.1-8b-instant
      api_key: os.environ/GROQ_API_KEY
  - model_name: "[Groq] Llama 3 (70B)"
    litellm_params:
      model: groq/llama3-70b-8192
      api_key: os.environ/GROQ_API_KEY
  - model_name: "[Groq] Llama 3 (8B)"
    litellm_params:
      model: groq/llama3-8b-8192
      api_key: os.environ/GROQ_API_KEY
  - model_name: "[Groq] Llava 1.5 (7B)"
    litellm_params:
      model: groq/llava-v1.5-7b-4096-preview
      api_key: os.environ/GROQ_API_KEY
  - model_name: "[Groq] Mixtral (8x7B)"
    litellm_params:
      model: groq/mixtral-8x7b-32768
      api_key: os.environ/GROQ_API_KEY